# Site settings
title      : Boba Fett's resume
email      : boba@deathstar.gal
description: 
baseurl    : "/Boba-Fett-Theme-For-Jekyll"
url        : "http://www.leoderbois.com/Boba-Fett-Theme-For-Jekyll/"


metadata: ["Leo Derbois","github","jekyll","jekyllrb","resume","CV","Boba Fett"]
############################# Personnal Inforamtions ################################

name   : Boba Fett
summary: Intergalactic Hit Man 
quote  : "kill and kidnap people are all my life. My father selects me because was the best in a million of sons. I was made and educate to kill, kidnap and guard your body like nobody can do better than me !"
phone  : +33 06 71 82 84 56

# Where you leave ?
street : 45 Wookies street
city   : Kamino			
zipcode: 45002				


# if you have a site or a custom blog
blog_name: Boba Fett At School
blog_url : http://www.osxbricks.com

linkedin: bobafett # linkedin username
google  : bobafett # google username
github  : bobafett # github username
twitter : bobafett # twitter username
facebook: bobafett # facebook username


############################# Site Options ################################
favicon         : /assets/bobafett.ico 		# Favicon website
avatar          : /assets/bobafett.jpg 		# Avatar/photo 
panel_background: /assets/slave_one.png 	# panel background images
enable_ribbon   : yes 						# remove this line to remove the ribbon


############################ Resume Content ################################
# Hobbies
#if you remove this, articles with 'hobbies' category are considerated
hobbies: ["Pod Racer Competition", "Computer Sciences","Women","Cooking for friends"]


# Kills
#if you remove this, articles with 'skills' category are considerated
skills:
- name: Weapons
  values: ["Blasters","Heavy ranged","Melee"]
- name: Spacecraft
  values: ["Slave I & II","A-WING FIGHTER","AAT BATTLE TANK"]
- name: Cooking specialties
  values: ["Cookies","Asian food","Snails"]

# Inforamtions
informations-custom:
- text: Space ship drive Licence + vehicle
  logo: space-shuttle
- text: Cooking Wookie stuff
  logo: spoon
- text: Have a lot of guns

speaking-langugages: ["Mandalorian (native)","Huttese (professionnal)","Wookie (bases)"]

# PDF version of your resume 
resume_pdf: http://inft.ly/k2FShYv.png


############################# Build setting (don't touch!) ################################
markdown: kramdown
permalink: pretty

############################# Plugins ################################

# RAS
